# These are supported funding model platforms

github: [ted-marozzi]
custom: [https://www.paypal.com/donate/?business=2QM4NDPG2SLNN&no_recurring=0&item_name=Help+support+Mermaid+Flow%21+If+you+use+Mermaid+Flow+for+any+commercial+reasons+please+donate+to+fund+its+development.&currency_code=AUD]
